### ISSUE TITLE
TypeError: plot() got an unexpected keyword argument 'config'

### ISSUE THREAD

**Issue by mazzma12** [ghtmtt/DataPlotly#82]
Hi,

I tried to run a simple Scatter plot following the documentation I  got this Traceback : 

```python
2018-10-05T17:29:41     WARNING    Traceback (most recent call last):
              File "/home/matthieu/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DataPlotly/data_plotly_dialog.py", line 1012, in createPlot
              self.plot_path = self.plotobject.buildFigure()
              File "/home/matthieu/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DataPlotly/data_plotly_plot.py", line 663, in buildFigure
              self.raw_plot += plotly.offline.plot(fig, output_type='div', include_plotlyjs=False, show_link=False, config=config)
             TypeError: plot() got an unexpected keyword argument 'config'
```

I run QGIS version 3.2 on Ubuntu 16.04 and the plotly version used in QGIS python shell is  '1.9.5'

**Comment by mazzma12** [comment]
I found out that I have an old version of plotly installed system wide and the wiki specifiies : 

> WARNING: Dataplotly works with plotly versions >= 2.0.13

I would like to install it in a virtual environment but haven't managed to find a way yet

**Comment by ghtmtt** [comment]
Not so easy to have a venv working with QGIS. But this is an upstream problem :)

**Comment by mazzma12** [comment]
Definitely not related to your plugin ofc !
